### PR TITLE
Update client.lua

### PR DESCRIPTION
**Pull request by Emotion06**
The notifications do not work without this function.

### CODE REVIEW

**Comment by KadDarem** [comment]
Right.
This function bigInt is included in dataview module.
It's better to check if this module is loaded than add functions here.

**Comment by Emotion06** [comment]
Oh, all right, that means just load in the dataview module?

**Comment by KadDarem** [comment]
Yes.

**Comment by KadDarem** [comment]
Updated in the v1.1.1

**Comment by KadDarem** [comment]
Update to close it

**Pull request closed without merging**
